name: streamlit app Update

on:
  push:
    paths:
      - 'UNO Service Learning Data Sheet De-Identified Version.xlsx'
  
jobs:
  update-app:
    runs-on: ubuntu-latest

    steps:
      #  Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run app since cleaning occurs in same file
      - name: Run Script
        run: python streamlit_app.py

      # Commit and Push Updated Data
      - name: Commit and Push Changes streamlit_app.py
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add streamlit_app.py
          git commit -m "Auto-update streamlit_app.py from Excel data"
          git push
        continue-on-error: true
